changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"