name: renovate

on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.62.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}